[package]
name = "nrfutil-rs"
version = "0.1.0"
authors = ["Lotte Steenbrink <lotte.steenbrink@ferrous-systems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
